Describe the logic of game
syaaav/cards pull request #4
Opened 2022-05-19 13:16 UTC by syaaav

Added functions for opening cards, starting a timer, counting identical pairs and comparing selected pairs.

2022-05-20 07:41 UTC, mrerberg requested changes

2022-05-20 07:41 UTC, mrerberg commented on .gitignore
> +webpack.config.js
webpack.config.js, package.json, package-lock.json, static/

Это все нужно в исходном коде. Ты же не собираешься у себя все локально хранить? А как другие разрабы будут собирать проект?

2022-05-20 07:41 UTC, mrerberg commented on package.json
> +    "lint:scss": "stylelint './**/*.scss'",
А что у тебя в проекте разные файлы используются? И css, и scss?

2022-05-20 07:41 UTC, mrerberg commented on screen_Game.js
> +  // window.application.renderBlock('topMenu', topMenu);
Мертвый код следует удалить

2022-05-20 07:41 UTC, mrerberg commented on screen_Game.js
> +  const timeMin = document.createElement('div');
Может сделать абстрактную функцию, которая будет принимать некую структуру данных и по ней генерировать и вставлять элемент на страницу?

2022-05-20 07:41 UTC, mrerberg commented on screen_Game.js
> +  const arrRanks = ['A', 'K', 'Q', 'J', '10', '9', '8', '7', '6'];
Эти данные выглядят как программные константы, а значит, можно вынести из функции. Мало ли где еще пригодятся?

2022-05-20 07:41 UTC, mrerberg commented on screen_Game.js
> +  cardsBody.forEach((card) => {
Я бы навешивал 1 класс и по нему бы скрывал все остальные элементы. Это можно через css сделать

2022-05-20 07:41 UTC, mrerberg commented on screen_Game.js
> +export { renderScreenGame, renderTopMenu, renderCards, hideCards };
Данный файл получился очень большой. Его следует разбить на несколько маленьких, а большие функции тоже стоит дробить

2022-05-20 07:41 UTC, mrerberg commented on style.scss
> +    background-color: #c2f5ff;
Есть смысл вынести все цвета в scss переменные

2022-05-23 18:28 UTC, syaaav commented on screen_Game.js
> +  // window.application.renderBlock('topMenu', topMenu);
Удалила

2022-05-23 18:28 UTC, syaaav commented on screen_Game.js
> +  const timeMin = document.createElement('div');
Спасибо! Сделала)

2022-05-23 18:29 UTC, syaaav commented on screen_Game.js
> +export { renderScreenGame, renderTopMenu, renderCards, hideCards };
Разбила файл на 2 и функции на несколько маленьких

2022-05-23 18:29 UTC, syaaav commented on style.scss
> +    background-color: #c2f5ff;
Вынесла, спасибо!

2022-05-23 18:30 UTC, syaaav commented on screen_Game.js
> +  cardsBody.forEach((card) => {
Не поняла, что имеется в виду. Я добавила класс hidden и по нему скрыла элементы через css

2022-05-23 18:32 UTC, syaaav commented on package.json
> +    "lint:scss": "stylelint './**/*.scss'",
Только scss. Удалила лишнее

2022-05-25 07:42 UTC, mrerberg requested changes

2022-05-25 07:42 UTC, mrerberg commented on style.scss
> +$font-family: 'Oswald', sans-serif;
Переменные стоит вынести в отдельный файл. Так проще с ними работать и их искать

2022-05-25 07:42 UTC, mrerberg commented on screen_Game.js
> +const arrRanks = ['A', 'K', 'Q', 'J', '10', '9', '8', '7', '6'];
Для таких констант, кстати, можно завести прям файл constants.js, так как это очень важные для приложения константы

2022-05-25 07:42 UTC, mrerberg commented on screen_Game.js
> +import { createNewEl } from './screen_Start.js';
Названия файлов очень специфичные. Обычно используют

camelCase
kebab-case
snake_case

У тебя же получился  snake_Case. Да, консистентно, ты везде так именуешь, но на всякий случай)

2022-05-25 07:42 UTC, mrerberg commented on logic_Game.js
> +function hideCards() {
Это функция очень большая, ее бы разбить на несколько

2022-05-25 07:42 UTC, mrerberg commented on logic_Game.js
> +  cardsBody.forEach((card) => {
Мой коммент был про то, что можно корневому элементу карточки давать класс hidden, а дальше через css

```css
.hidden .card-top {}
.hidden .card-bottom {}
```

2022-05-25 07:42 UTC, mrerberg commented on logic_Game.js
> +// Variables
Лишний коммент. Старайся не писать комменты там, где и так все понятно. Обычно комменты стараются ставить, чтобы объяснить, почему было сделано так, а не иначе

2022-05-25 12:00 UTC, syaaav commented on style.scss
> +$font-family: 'Oswald', sans-serif;
Вынесла в файл variables.scss и импортировала в style.scss

2022-05-25 12:00 UTC, syaaav commented on screen_Game.js
> +const arrRanks = ['A', 'K', 'Q', 'J', '10', '9', '8', '7', '6'];
Сделала)

2022-05-25 12:01 UTC, syaaav commented on screen_Game.js
> +import { createNewEl } from './screen_Start.js';
Спасибо! Закончу этот проект уже так, но в будущем буду писать правильно)

2022-05-25 12:03 UTC, syaaav commented on logic_Game.js
> +function hideCards() {
Разбила на 3 функции: hideCards, saveCards и compareCards.

2022-05-25 12:03 UTC, syaaav commented on logic_Game.js
> +  cardsBody.forEach((card) => {
Сделала, спасибо!)

2022-05-31 14:49 UTC, merged